name: Platzom CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm test
      - name: Print Github Token
        run: echo ${{ secret.GITHUB_TOKEN }}
